### ISSUE TITLE
Need test programs with traits and classes

### ISSUE THREAD

**Issue by alexschneider** [alexschneider/teascript#21]
We don't currently have any programs that test traits and classes, so we probably should be doing so.

**Comment by rachelriv** [comment]
Great idea! Do you think you could take a shot at it?

**Comment by alexschneider** [comment]
I'd like to, if I've got time. My time is pretty limited over the next week or so though, so I wanted to write down everything that we would need so that if I don't get to it, others know what needs to be done.

**Comment by rachelriv** [comment]
We've got some tests for classes and traits now.

We should probably try to make them more comprehensive, but then again, we should make everything more comprehensive. :smile: 

I'm going to close this issue.
