### ISSUE TITLE
Variable declaration should be two tokens or have more annotations

### ISSUE THREAD

**Issue by alexschneider** [alexschneider/teascript#24]
To aid potential optional typing, we should have our variable declarations be one of the two options:
1. two separate tokens (optionally separated by a type token) - a `:` and `=` token.
2. A `vardec` token with the `type` attribute. 

Option 1 is fine if we want to handle that in the parser, but if we want to handle it in the scanner, option 2 is best. 

Right now, if we have the statement `x : int = 5`, we get the following scanner output:

``` javascript
[ { lexeme: 'x', kind: 'ID', start: 0, lineNumber: 0 },
  { lexeme: ':', kind: ':', start: 2, lineNumber: 0 },
  { lexeme: 'int', kind: 'int', start: 4, lineNumber: 0 },
  { lexeme: '=', kind: '=', start: 8, lineNumber: 0 },
  { lexeme: '5', kind: 'INTLIT', start: 10, lineNumber: 0 },
  { kind: 'EOF', lexeme: 'EOF', start: 0 } ]
```

But if we have the statement `x := 5`, we get the following scanner output:

``` javascript
[ { lexeme: 'x', kind: 'ID', start: 0, lineNumber: 0 },
  { lexeme: ':=', kind: ':=', start: 2, lineNumber: 0 },
  { lexeme: '5', kind: 'INTLIT', start: 5, lineNumber: 0 },
  { kind: 'EOF', lexeme: 'EOF', start: 0 } ]
```

Thoughts/suggestions?

**Comment by juansc** [comment]
Can I see an example of option 2?

**Comment by alexschneider** [comment]
I'm unsure how we'd go about it. 

Possibly the object would look like:

``` javascript
{ lexeme: ': int =', kind: 'VARDEC', type: 'int', start: 2, lineNumber: 0 }
```

Without type annotations:

``` javascript
{ lexeme: ':=', kind: 'VARDEC', start: 2, lineNumber: 0 }
```

Open for suggestions.

**Comment by rtoal** [comment]
You wouldn't put a type on a token.

What is VARDEC? A ":="?

**Comment by alexschneider** [comment]
Yea, I didn't like that idea either. It's probably best to handle in the parser.

**Comment by alexschneider** [comment]
@rtoal: BTW, is it OK to have linenumbers on a token?

**Comment by rtoal** [comment]
Yes, the line numbers and column numbers show where the token is in the source code. Also important are the kind of the token and its lexeme. All those are inherent properties of the token.

The "type" field, if I understood your use of it correctly, seemed to be related to the language's semantics, and not its lexis. I don't feel it is appropriate to do type inference during lexical analysis.

If you meant something _else_ by "type", let me know; there may be a way to use it.

**Comment by alexschneider** [comment]
We got rid of optional typing, no longer relevant.
