### ISSUE TITLE
Should types in the scanner be IDs?

### ISSUE THREAD

**Issue by alexschneider** [alexschneider/teascript#25]
Currently the following program:

```
x : foo = 5
```

Scans as 

``` javascript
[ { lexeme: 'x', kind: 'ID', start: 0, lineNumber: 0 },
  { lexeme: ':', kind: ':', start: 2, lineNumber: 0 },
  { lexeme: 'foo', kind: 'ID', start: 4, lineNumber: 0 },
  { lexeme: '=', kind: '=', start: 8, lineNumber: 0 },
  { lexeme: '5', kind: 'INTLIT', start: 10, lineNumber: 0 },
  { kind: 'EOF', lexeme: 'EOF', start: 0 } ]
```

I'd be fine if we treat non-builtin types as IDs, but I just wanted to make sure that's the general consensus and expected behavior, or if someone sees any potential problems.

**Comment by rtoal** [comment]
This is completely correct. Whether the ID foo is properly bound to a type entity is to be determined at semantic analysis time.
