### ISSUE TITLE
Should we reduce the amount of overloading we do?

### ISSUE THREAD

**Issue by alexschneider** [alexschneider/teascript#33]
Right now we overload the following:

```
()
:
[] - not as much
```

Should we come up with alternative syntax for representing these?

**Comment by rachelriv** [comment]
I feel like our parens overloading is fine as most languages allow for parenthesized expressions as well as parenthesize arguments/parameters. Alternative ways of using parentheses (or lack of ways) seems a little unintuitive to me.

**Comment by alexschneider** [comment]
I guess that's fine, the only major issue is dealing with tuples and argument destructuring, but it sounds like you have a good handle on that. 

What about `:` overloading?

**Comment by rachelriv** [comment]
Well we still need to have a group discussion about tuple syntax.

The `:` overloading doesn't bother me, but we can have a group vote tomorrow!

**Comment by alexschneider** [comment]
@rachelriv I think we resolved the tuple syntax, right? If not, please reopen.
