### ISSUE TITLE
Parser doesn't support assigning to a variable reference

### ISSUE THREAD

**Issue by whusted** [alexschneider/teascript#59]
For example:

```
z[0] = 'hi'

```

doesn't parse. While I thought this looked simple to account for in the beginning, my esteemed colleague, and the back to back to back MVP of the LMU CS program, @rachelriv, brought up examples of why this is something we all need to think/talk about

**Comment by whusted** [comment]
A quick thought on what the function might look like (courtesy of the aforementioned @rachelriv):

```
parseVarRef = ->
  console.log "Parseing Variable Reference"
  exp = parseExp8()

  while ((at ['.', '[']) and
  (next StartTokens.expression))
    if at '.'
      match '.'
      exp = new MemberAccess exp, parseExpression()
    else if at '['
      match '['
      exp = new ListSubscript exp, parseExpression()
      match ']'

  if at([ '++', '--' ])
    op = match()
    exp = new PostUnaryExpression op, exp
  exp
```

**Comment by juansc** [comment]
We removed unary increments and decrements when we merged exponents.

**Comment by rachelriv** [comment]
We've got this working now!
