### ISSUE TITLE
Program2.tea isn't a valid program

### ISSUE THREAD

**Issue by alexschneider** [alexschneider/teascript#68]
All functions should have an `end` at the end of them

https://github.com/alexschneider/teascript/blob/master/test/example/input_programs/valid_programs/program2.tea

Not necessary because it's testing the scanner, but it'd be nice if all our valid programs were valid programs.

**Comment by rtoal** [comment]
I would say it _is_ necessary because the path name of this file does not include any indication that it is a scanner test. Therefore anyone looking at this file would think the file is valid teascript.

**Comment by rachelriv** [comment]
I just suggested to @whusted and @juansc that we have separate directories within the `valid` and `invalid` example program directions for the scanner, parser, etc. Then we might have the same program in the `valid/scanner/` directory and the `invalid/parser/` directory.

**Comment by alexschneider** [comment]
I think that might get too confusing - I'd rather all our valid programs be completely valid.

**Comment by rachelriv** [comment]
The tests have been refactored so that it is clear when a program is only valid for scanning, parsing, etc.
