### ISSUE TITLE
Missing Operators

### ISSUE THREAD

**Issue by juansc** [alexschneider/teascript#7]
@rachelriv  @alexschneider  @whusted  I realized the following tokens are not included in our scanner.

``` javascript
'^', '&', '|' // bitwise operators
'+=' , '-=', '*=', '\=' // mutators
'++', '--'
'%' // Modulo operator
'return' // This seems like a must.
```

Will these be included in our language?

**Comment by rtoal** [comment]
Good find. You can add them. Don't forget to add tests.

**Comment by rachelriv** [comment]
Yup, looks like we need those. Go ahead and add them in the tokens class. That should be all you have to do.

**Comment by juansc** [comment]
Created a pull request. Will continue making sample code and see if we're missing anything else.
